# This is a basic workflow to help you get started with Actions

name: Evaluate Image Classifier

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request if image-classifier.ipynb has changed
  pull_request:
    paths:
      - 'notebooks/image-classifier.ipynb'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Allow job to write PR comments
    permissions:
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Restore cache of Python environment (if available)
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }} #see https://github.com/actions/setup-python/pull/418
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
          
      # Run pip install using requirements.txt
      - name: pip install requirements
        run: python3 -m pip install -r requirements.txt

      # Test the model
      - uses: yaananth/run-notebook@v2
        env:
          RUNNER: ${{ toJson(runner) }}
          SECRETS: ${{ toJson(secrets) }}
          GITHUB: ${{ toJson(github) }}
        with:
          notebook: "notebooks/image-classifier.ipynb"
          isReport: True
          poll: False

      # extract model accuracy from output
      - run: >
          grep '^Accuracy for class' ${{ RUNNER.temp }}/nb-runner/image-classifier.html
          >> ${{ RUNNER.temp }}/nb-runner/image-classifier-accuracy.txt
      
      # Creat PR comment
      - uses: mshick/add-pr-comment@v2
        env:
          RUNNER: ${{ toJson(runner) }}
        with:
          message-path: ${{ RUNNER.temp }}/nb-runner/image-classifier-accuracy.txt
