# This is a basic workflow to help you get started with Actions

name: Evaluate Image Classifier

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request if image-classifier.ipynb has changed
  pull_request:
    paths:
      - 'notebooks/image-classifier.ipynb'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Run pip install using requirements.txt
      - name: pip install requirements
        run: python3 -m pip install -r requirements.txt

      # Cache the Python environment 
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }} #see https://github.com/actions/setup-python/pull/418
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      # Test the model
      - uses: yaananth/run-notebook@v2
        with:
          notebook: "notebooks/image-classifier.ipynb"
          isReport: True
          poll: True
